'use client';
import { useEffect, useMemo, useState } from 'react';

type Staff={id:string,name:string,active:boolean};
type Vehicle={id:string,job_number:string,customer:string|null,vehicle_type:string,registration:string|null,vin:string|null,budget_hours:number,status:string,description:string|null,due_date:string|null,actual_finished_date:string|null};
type Entry={id:string,staff_id:string,vehicle_id:string,task:string,notes:string|null,started_at:string,ended_at:string|null,paused_at:string|null,total_paused_seconds:number,staff:{name:string},vehicles:{job_number:string,customer:string|null,vehicle_type:string,budget_hours:number,status:string,due_date:string|null,actual_finished_date:string|null}};
type Correction={id:string,time_entry_id:string,old_started_at:string,old_ended_at:string|null,new_started_at:string,new_ended_at:string|null,reason:string,corrected_at:string};
const tasks=['Engineering','Fabrication','Mechanical','Electrical','Assembly','Inspection / QA','Rework','Service','Other'];
const MELBOURNE_TZ='Australia/Melbourne';
const melDate=(value:string|number|Date)=>new Intl.DateTimeFormat('en-CA',{timeZone:MELBOURNE_TZ,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(value));
const melDateTime=(value:string|number|Date)=>new Intl.DateTimeFormat('en-AU',{timeZone:MELBOURNE_TZ,dateStyle:'short',timeStyle:'short'}).format(new Date(value));
const hours=(e:Entry,now:number)=>{const end=e.ended_at?new Date(e.ended_at).getTime():e.paused_at?new Date(e.paused_at).getTime():now;return Math.max(0,(end-new Date(e.started_at).getTime()-Number(e.total_paused_seconds||0)*1000)/3600000)};
const localInput=(iso:string|null)=>{if(!iso)return '';const parts=new Intl.DateTimeFormat('en-CA',{timeZone:MELBOURNE_TZ,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(iso));const get=(t:string)=>parts.find(p=>p.type===t)?.value||'';return `${get('year')}-${get('month')}-${get('day')}T${get('hour')}:${get('minute')}`};
const csvCell=(v:any)=>`"${String(v??'').replace(/"/g,'""')}"`;

export default function Home(){
  const [tab,setTab]=useState<'clock'|'vehicles'|'staff'|'dashboard'>('clock');
  const [staff,setStaff]=useState<Staff[]>([]),[vehicles,setVehicles]=useState<Vehicle[]>([]),[entries,setEntries]=useState<Entry[]>([]),[corrections,setCorrections]=useState<Correction[]>([]);
  const [staffId,setStaffId]=useState(''),[staffPin,setStaffPin]=useState(''),[vehicleId,setVehicleId]=useState(''),[task,setTask]=useState(''),[notes,setNotes]=useState('');
  const [message,setMessage]=useState(''),[now,setNow]=useState(Date.now());
  const [manager,setManager]=useState(false),[pin,setPin]=useState(''),[managerMsg,setManagerMsg]=useState('');
  const emptyVehicle={id:'',job_number:'',customer:'',vehicle_type:'Toyota HiAce',registration:'',vin:'',budget_hours:0,status:'Active',description:'',due_date:'',actual_finished_date:''};
  const [form,setForm]=useState<any>(emptyVehicle);
  const [staffForm,setStaffForm]=useState<any>({id:'',name:'',pin:'',active:true});
  const [range,setRange]=useState('week'),[fromDate,setFromDate]=useState(''),[toDate,setToDate]=useState('');
  const [reportVehicleId,setReportVehicleId]=useState('all'),[reportStaffId,setReportStaffId]=useState('all');
  const [editEntry,setEditEntry]=useState<Entry|null>(null),[editStart,setEditStart]=useState(''),[editEnd,setEditEnd]=useState(''),[editReason,setEditReason]=useState('');

  async function load(){const r=await fetch('/api/data',{cache:'no-store'});const j=await r.json();if(r.ok){setStaff(j.staff||[]);setVehicles(j.vehicles||[]);setEntries(j.entries||[]);setCorrections(j.corrections||[]);}else setMessage(j.error||'Could not load data.');}
  useEffect(()=>{load();const a=setInterval(load,15000),b=setInterval(()=>setNow(Date.now()),1000);return()=>{clearInterval(a);clearInterval(b)}},[]);

  const active=entries.filter(e=>!e.ended_at),completed=entries.filter(e=>e.ended_at),activeStaff=staff.filter(s=>s.active),activeVehicles=vehicles.filter(v=>v.status==='Active');
  const totalHours=entries.reduce((s,e)=>s+hours(e,now),0);
  const vehicleTotals=useMemo(()=>vehicles.map(v=>({...v,hours:entries.filter(e=>e.vehicle_id===v.id).reduce((s,e)=>s+hours(e,now),0)})),[vehicles,entries,now]);

  const rangeBounds=useMemo(()=>{
    const today=melDate(now);
    const addDays=(key:string,n:number)=>{const d=new Date(key+'T00:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)};
    let start:string|null=null,end:string|null=null;
    if(range==='today'){start=today;end=addDays(today,1);}
    if(range==='week'){const d=new Date(today+'T00:00:00Z');const day=(d.getUTCDay()+6)%7;start=addDays(today,-day);end=addDays(start,7);}
    if(range==='month'){start=today.slice(0,7)+'-01';const d=new Date(start+'T00:00:00Z');d.setUTCMonth(d.getUTCMonth()+1);end=d.toISOString().slice(0,10);}
    if(range==='custom'){start=fromDate||null;end=toDate?addDays(toDate,1):null;}
    return {start,end};
  },[range,fromDate,toDate,now]);

  const filteredEntries=useMemo(()=>completed.filter(e=>{
    const t=melDate(e.started_at);
    if(rangeBounds.start&&t<rangeBounds.start)return false;
    if(rangeBounds.end&&t>=rangeBounds.end)return false;
    if(reportVehicleId!=='all'&&e.vehicle_id!==reportVehicleId)return false;
    if(reportStaffId!=='all'&&e.staff_id!==reportStaffId)return false;
    return true;
  }),[completed,rangeBounds,reportVehicleId,reportStaffId]);
  const filteredHours=filteredEntries.reduce((s,e)=>s+hours(e,now),0);

  async function start(){setMessage('');const r=await fetch('/api/start',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({staff_id:staffId,staff_pin:staffPin,vehicle_id:vehicleId,task,notes})});const j=await r.json();if(!r.ok){setMessage(j.error||'Could not start job.');return;}setStaffPin('');setTask('');setNotes('');setMessage('Job started.');await load();}
  async function stop(id:string){const r=await fetch('/api/stop',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({entry_id:id})});const j=await r.json();if(r.ok){setStaffId('');setStaffPin('');setVehicleId('');setTask('');setNotes('');setMessage('Time saved. Staff logged out.');}else setMessage(j.error||'Could not stop job.');await load();}
  async function pauseResume(id:string,action:'pause'|'resume'){setMessage('');const r=await fetch('/api/pause',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({entry_id:id,action})});const j=await r.json();if(!r.ok)setMessage(j.error||'Could not update timer.');else setMessage(action==='pause'?'Job paused.':'Job resumed.');await load();}
  async function systemAction(action:'reset_pins'|'clear_time'|'clear_time_vehicles'){const labels={reset_pins:'Reset ALL staff PINs? Staff will be unable to start work until new PINs are assigned.',clear_time:'Permanently delete ALL time entries and correction history? Staff and vehicles will be kept.',clear_time_vehicles:'Permanently delete ALL time entries, correction history and vehicle records? Staff will be kept.'};if(!confirm(labels[action]))return;const confirm2=prompt('Type RESET to confirm this action.');if(confirm2!=='RESET'){setManagerMsg('Reset cancelled.');return;}const r=await fetch('/api/manager/system',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action})});const j=await r.json();if(!r.ok){setManagerMsg(j.error||'System action failed.');return;}setManagerMsg(action==='reset_pins'?'All staff PINs have been cleared. Assign new PINs below.':'Selected current data has been cleared.');await load();}
  async function login(){const r=await fetch('/api/manager/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pin})});const j=await r.json();if(r.ok){setManager(true);setPin('');setManagerMsg('Manager access unlocked.')}else setManagerMsg(j.error||'Login failed.');}
  async function saveVehicle(){const r=await fetch('/api/manager/vehicle',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const j=await r.json();if(!r.ok){setManagerMsg(j.error||'Could not save vehicle.');return;}setManagerMsg('Vehicle saved.');setForm(emptyVehicle);await load();}
  async function saveStaff(){const r=await fetch('/api/manager/staff',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(staffForm)});const j=await r.json();if(!r.ok){setManagerMsg(j.error||'Could not save staff member.');return;}setManagerMsg(staffForm.id?'Staff member updated.':'Staff member added.');setStaffForm({id:'',name:'',pin:'',active:true});await load();}
  function beginCorrection(e:Entry){setEditEntry(e);setEditStart(localInput(e.started_at));setEditEnd(localInput(e.ended_at));setEditReason('');setManagerMsg('');}
  async function saveCorrection(){if(!editEntry)return;const r=await fetch('/api/manager/time-entry',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:editEntry.id,started_at:editStart,ended_at:editEnd,reason:editReason})});const j=await r.json();if(!r.ok){setManagerMsg(j.error||'Could not correct time entry.');return;}setManagerMsg('Time entry corrected and audit record saved.');setEditEntry(null);setEditReason('');await load();}
  function exportCsv(){
    const rows=[['Date','Employee','Job','Vehicle','Customer','Task','Notes','Start','Finish','Hours'],...filteredEntries.map(e=>[
      melDate(e.started_at),e.staff.name,e.vehicles.job_number,e.vehicles.vehicle_type,e.vehicles.customer||'',e.task,e.notes||'',melDateTime(e.started_at),e.ended_at?melDateTime(e.ended_at):'',hours(e,now).toFixed(2)
    ])];
    const csv=rows.map(r=>r.map(csvCell).join(',')).join('\r\n');
    const blob=new Blob([csv],{type:'text/csv;charset=utf-8;'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`enduroco-labour-${melDate(now)}.csv`;a.click();URL.revokeObjectURL(url);
  }

  return <main className="wrap">
    <h1>EnduroCo Vehicle Time Tracker</h1><p className="muted">Shared workshop labour tracking · All displayed times are Victoria, Australia time.</p>
    <div className="tabs"><button className={tab==='clock'?'active':''} onClick={()=>setTab('clock')}>Staff Time Clock</button><button className={tab==='vehicles'?'active':''} onClick={()=>setTab('vehicles')}>Manager Vehicles</button><button className={tab==='staff'?'active':''} onClick={()=>setTab('staff')}>Manager Staff</button><button className={tab==='dashboard'?'active':''} onClick={()=>setTab('dashboard')}>Manager Dashboard</button></div>

    {tab==='clock' && <><div className="metrics"><div className="metric">Active workers<b>{active.length}</b></div><div className="metric">Active vehicles<b>{new Set(active.map(e=>e.vehicle_id)).size}</b></div><div className="metric">Recorded hours<b>{totalHours.toFixed(1)}</b></div><div className="metric">Completed entries<b>{completed.length}</b></div></div><div className="card clock-panel"><h2>Start work on a vehicle</h2><div className="grid"><div className="field"><label>Employee</label><select value={staffId} onChange={e=>setStaffId(e.target.value)}><option value="">Select employee</option>{activeStaff.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div><div className="field"><label>4-digit Staff PIN</label><input type="password" inputMode="numeric" maxLength={4} value={staffPin} onChange={e=>setStaffPin(e.target.value.replace(/\D/g,'').slice(0,4))} placeholder="PIN"/></div><div className="field"><label>Vehicle / Job</label><select value={vehicleId} onChange={e=>setVehicleId(e.target.value)}><option value="">Select vehicle</option>{activeVehicles.map(v=><option key={v.id} value={v.id}>{v.job_number} — {v.vehicle_type}{v.customer?' — '+v.customer:''}</option>)}</select></div><div className="field"><label>Task</label><select value={task} onChange={e=>setTask(e.target.value)}><option value="">Select task</option>{tasks.map(t=><option key={t}>{t}</option>)}</select></div><div className="field"><label>Notes</label><input value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Optional"/></div></div><p className={message.includes('saved')||message.includes('started')||message.includes('paused')||message.includes('resumed')?'success':'danger'}>{message}</p><button className="btn primary full tablet-primary" onClick={start}>START JOB</button></div><div className="card"><h2>Currently working</h2>{active.length===0?<p className="muted">Nobody is currently clocked onto a vehicle.</p>:active.map(e=><div className={'entry active-job '+(e.paused_at?'paused':'')} key={e.id}><div className="row"><div><b>{e.staff.name}</b><div>{e.vehicles.job_number} — {e.vehicles.vehicle_type}</div><div className="muted">{e.task}{e.notes?' · '+e.notes:''}</div><div className="muted">Started {melDateTime(e.started_at)} (Victoria)</div></div><div><span className={'pill '+(e.paused_at?'pause-pill':'')}>{e.paused_at?'PAUSED':'LIVE'}</span><div className="big">{hours(e,now).toFixed(2)} hrs</div></div></div><div className="clock-actions"><button className="btn pause-btn" onClick={()=>pauseResume(e.id,e.paused_at?'resume':'pause')}>{e.paused_at?'RESUME':'PAUSE'}</button><button className="btn stop-btn" onClick={()=>stop(e.id)}>STOP JOB</button></div></div>)}</div></>}

    {tab==='vehicles' && <ManagerGate manager={manager} pin={pin} setPin={setPin} login={login} msg={managerMsg}><><div className="card"><h2>Add / edit vehicle</h2><div className="grid">{['job_number','customer','registration','vin','description'].map(k=><div className="field" key={k}><label>{k.replace('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}</label><input value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></div>)}<div className="field"><label>Vehicle Type</label><select value={form.vehicle_type} onChange={e=>setForm({...form,vehicle_type:e.target.value})}><option>Toyota HiAce</option><option>Toyota Coaster</option><option>Other</option></select></div><div className="field"><label>Budgeted Labour Hours</label><input type="number" value={form.budget_hours} onChange={e=>setForm({...form,budget_hours:Number(e.target.value)})}/></div><div className="field"><label>Vehicle Due Date</label><input type="date" value={form.due_date||''} onChange={e=>setForm({...form,due_date:e.target.value})}/></div><div className="field"><label>Actual Finish Date</label><input type="date" value={form.actual_finished_date||''} onChange={e=>setForm({...form,actual_finished_date:e.target.value})}/><div className="muted">Automatically set to today when first marked Completed if left blank.</div></div><div className="field"><label>Status</label><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>Active</option><option>On Hold</option><option>Completed</option></select></div></div><p>{managerMsg}</p><div className="actions"><button className="btn primary" onClick={saveVehicle}>{form.id?'UPDATE VEHICLE':'SAVE VEHICLE'}</button><button className="btn" onClick={()=>setForm(emptyVehicle)}>CLEAR</button></div></div><div className="card"><h2>Vehicle register</h2>{vehicleTotals.map(v=>{const today=melDate(now);const overdue=v.status!=='Completed'&&!!v.due_date&&v.due_date<today;const timing=v.status==='Completed'&&v.due_date&&v.actual_finished_date?(v.actual_finished_date<v.due_date?'Finished early':v.actual_finished_date===v.due_date?'Finished on time':'Finished late'):'';return <div className="entry" key={v.id}><div className="row"><div><b>{v.job_number} — {v.vehicle_type}</b><div>{v.customer||'No customer'}</div><div className="muted">{v.status} · {v.description||'No description'}</div><div>Due: <b>{v.due_date||'Not set'}</b>{overdue?<span className="danger"> · OVERDUE</span>:null}</div><div>Actual finish: <b>{v.actual_finished_date||'Not finished'}</b>{timing?<span className="muted"> · {timing}</span>:null}</div></div><div><b>{v.hours.toFixed(2)} hrs</b><div className="muted">Budget {Number(v.budget_hours||0).toFixed(1)} hrs</div></div></div><button className="btn" onClick={()=>setForm(v)}>Edit</button></div>})}</div></></ManagerGate>}

    {tab==='staff' && <ManagerGate manager={manager} pin={pin} setPin={setPin} login={login} msg={managerMsg}><><div className="card"><h2>Staff Management</h2><p className="muted">Add staff and assign or reset their 4-digit PIN. Existing PINs are never displayed.</p><div className="grid"><div className="field"><label>Employee name</label><input value={staffForm.name} onChange={e=>setStaffForm({...staffForm,name:e.target.value})}/></div><div className="field"><label>{staffForm.id?'New PIN (leave blank to keep current PIN)':'4-digit PIN'}</label><input type="password" inputMode="numeric" maxLength={4} value={staffForm.pin} onChange={e=>setStaffForm({...staffForm,pin:e.target.value.replace(/\D/g,'').slice(0,4)})}/></div><div className="field"><label>Status</label><select value={staffForm.active?'Active':'Inactive'} onChange={e=>setStaffForm({...staffForm,active:e.target.value==='Active'})}><option>Active</option><option>Inactive</option></select></div></div><p>{managerMsg}</p><div className="actions"><button className="btn primary" onClick={saveStaff}>{staffForm.id?'UPDATE STAFF':'ADD STAFF'}</button><button className="btn" onClick={()=>setStaffForm({id:'',name:'',pin:'',active:true})}>CLEAR</button><button className="btn danger-btn" onClick={()=>systemAction('reset_pins')}>RESET ALL STAFF PINS</button></div></div><div className="card"><h2>Staff register</h2>{staff.map(s=><div className="entry" key={s.id}><div className="row"><div><b>{s.name}</b><div className="muted">{s.active?'Active':'Inactive'}</div></div><button className="btn" onClick={()=>setStaffForm({id:s.id,name:s.name,pin:'',active:s.active})}>Edit / Reset PIN</button></div></div>)}</div></></ManagerGate>}

    {tab==='dashboard' && <ManagerGate manager={manager} pin={pin} setPin={setPin} login={login} msg={managerMsg}><>
      <div className="metrics"><div className="metric">Filtered labour<b>{filteredHours.toFixed(1)}</b></div><div className="metric">Time entries<b>{filteredEntries.length}</b></div><div className="metric">Active jobs<b>{vehicles.filter(v=>v.status==='Active').length}</b></div><div className="metric">Over budget<b>{vehicleTotals.filter(v=>Number(v.budget_hours)>0&&v.hours>Number(v.budget_hours)).length}</b></div></div>
      <div className="card"><div className="row"><div><h2>Reporting filters</h2><p className="muted">Filter completed labour records before reviewing or exporting them.</p></div><button className="btn primary" onClick={exportCsv} disabled={!filteredEntries.length}>EXPORT CSV</button></div><div className="grid"><div className="field"><label>Date range</label><select value={range} onChange={e=>setRange(e.target.value)}><option value="today">Today</option><option value="week">This week</option><option value="month">This month</option><option value="all">All time</option><option value="custom">Custom dates</option></select></div><div className="field"><label>Vehicle</label><select value={reportVehicleId} onChange={e=>setReportVehicleId(e.target.value)}><option value="all">All vehicles</option>{vehicles.map(v=><option key={v.id} value={v.id}>{v.job_number} — {v.vehicle_type}</option>)}</select></div><div className="field"><label>Employee</label><select value={reportStaffId} onChange={e=>setReportStaffId(e.target.value)}><option value="all">All staff</option>{staff.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div>{range==='custom'&&<><div className="field"><label>From</label><input type="date" value={fromDate} onChange={e=>setFromDate(e.target.value)}/></div><div className="field"><label>To</label><input type="date" value={toDate} onChange={e=>setToDate(e.target.value)}/></div></>}</div></div>
      <div className="card"><h2>Labour & delivery by vehicle</h2><div className="table-wrap"><table className="table"><thead><tr><th>Job</th><th>Vehicle</th><th>Due</th><th>Finished</th><th>Delivery</th><th>Actual</th><th>Budget</th><th>Variance</th></tr></thead><tbody>{vehicleTotals.map(v=>{const b=Number(v.budget_hours||0),variance=b?v.hours-b:0;const today=melDate(now);let delivery='—';if(v.status==='Completed'&&v.due_date&&v.actual_finished_date) delivery=v.actual_finished_date<v.due_date?'Early':v.actual_finished_date===v.due_date?'On time':'Late';else if(v.status!=='Completed'&&v.due_date&&v.due_date<today) delivery='OVERDUE';return <tr key={v.id}><td>{v.job_number}</td><td>{v.vehicle_type}</td><td>{v.due_date||'—'}</td><td>{v.actual_finished_date||'—'}</td><td>{delivery}</td><td>{v.hours.toFixed(2)}</td><td>{b?b.toFixed(2):'—'}</td><td>{b?(variance>=0?'+':'')+variance.toFixed(2):'—'}</td></tr>})}</tbody></table></div></div>
      <div className="card"><h2>Filtered time entries</h2><p className="muted">Managers can correct completed entries. A reason is required and the original times are retained in the audit history.</p>{filteredEntries.length===0?<p className="muted">No entries match the selected filters.</p>:filteredEntries.map(e=><div className="entry" key={e.id}><div className="row"><div><b>{e.vehicles.job_number}</b><div>{e.staff.name} · {e.task}</div><div className="muted">{melDateTime(e.started_at)} → {e.ended_at?melDateTime(e.ended_at):''} (Victoria)</div>{e.notes?<div className="muted">{e.notes}</div>:null}</div><div><b>{hours(e,now).toFixed(2)} hrs</b><div><button className="btn" onClick={()=>beginCorrection(e)}>Correct time</button></div></div></div></div>)}</div>
      {editEntry&&<div className="card correction"><h2>Correct time entry</h2><p><b>{editEntry.staff.name}</b> · {editEntry.vehicles.job_number} · {editEntry.task}</p><div className="grid"><div className="field"><label>Start</label><input type="datetime-local" value={editStart} onChange={e=>setEditStart(e.target.value)}/></div><div className="field"><label>Finish</label><input type="datetime-local" value={editEnd} onChange={e=>setEditEnd(e.target.value)}/></div><div className="field"><label>Reason for correction</label><input value={editReason} onChange={e=>setEditReason(e.target.value)} placeholder="e.g. Staff forgot to stop timer"/></div></div><p className="danger">{managerMsg}</p><div className="actions"><button className="btn primary" onClick={saveCorrection}>SAVE CORRECTION</button><button className="btn" onClick={()=>setEditEntry(null)}>CANCEL</button></div></div>}
      <div className="card system-card"><h2>System maintenance</h2><p className="muted">Manager-only reset controls. Each action requires typing RESET before it will run.</p><div className="actions"><button className="btn danger-btn" onClick={()=>systemAction('clear_time')}>CLEAR ALL TIME RECORDS</button><button className="btn danger-btn" onClick={()=>systemAction('clear_time_vehicles')}>CLEAR TIME + VEHICLES</button></div><p className="danger">{managerMsg}</p></div>
      <div className="card"><h2>Time correction audit history</h2>{corrections.length===0?<p className="muted">No manager corrections have been made.</p>:corrections.slice(0,30).map(c=>{const e=entries.find(x=>x.id===c.time_entry_id);return <div className="entry" key={c.id}><b>{e?`${e.staff.name} · ${e.vehicles.job_number}`:'Time entry'}</b><div className="muted">Changed {melDateTime(c.corrected_at)} (Victoria) · {c.reason}</div><div>Old: {melDateTime(c.old_started_at)} → {c.old_ended_at?melDateTime(c.old_ended_at):'—'}</div><div>New: {melDateTime(c.new_started_at)} → {c.new_ended_at?melDateTime(c.new_ended_at):'—'}</div></div>})}</div>
    </></ManagerGate>}
  </main>
}

function ManagerGate({manager,pin,setPin,login,msg,children}:{manager:boolean,pin:string,setPin:(s:string)=>void,login:()=>void,msg:string,children:React.ReactNode}){if(manager)return <>{children}</>;return <div className="card manager-lock"><h2>Manager access</h2><p className="muted">Enter the manager PIN to manage staff, vehicles and reports.</p><div className="field"><label>Manager PIN</label><input type="password" inputMode="numeric" value={pin} onChange={e=>setPin(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')login()}}/></div><p className="danger">{msg}</p><button className="btn primary" onClick={login}>UNLOCK MANAGER AREA</button></div>}
